COMMENT ON COLUMN "public"."seasons"."season_id" IS 'Primary key for the seasons table.';
COMMENT ON COLUMN "public"."seasons"."season_name" IS 'The name of the season when the disputed resource was primarily used (e.g., ''Winter'', ''Summer'').';
COMMENT ON COLUMN "public"."communities"."community_id" IS 'Primary key for the communities table.';
COMMENT ON COLUMN "public"."communities"."community_name" IS 'The name of the community.';
COMMENT ON COLUMN "public"."communities"."parish_id" IS 'Foreign key linking to the parish this community belongs to.';
COMMENT ON COLUMN "public"."judgements"."judgement_id" IS 'Primary key for the judgements table.';
COMMENT ON COLUMN "public"."judgements"."sanction" IS 'The type of judgement or sanction handed down (e.g., ''Fined'').';
COMMENT ON COLUMN "public"."entries"."original_placename" IS 'The place''s name as written in the original source document.';
COMMENT ON COLUMN "public"."entries"."year" IS 'The year the event occurred, or if unknown, the year the matter was heard at court.';
COMMENT ON COLUMN "public"."entries"."description" IS 'Description of the event in free text. Can be multiple rows per event since each actor involved  has its own row';
COMMENT ON COLUMN "public"."entries"."reference_number" IS 'Reference number within a specific source collection, e.g., K.B. Wiklund''s transcripts.';
COMMENT ON COLUMN "public"."entries"."actor_id" IS 'Actor/participant in the event. If multiple actors are involved, each actor gets their own row.';
COMMENT ON COLUMN "public"."entries"."community_id" IS 'Foreign key linking to the community where the event took place.';
COMMENT ON COLUMN "public"."entries"."source_id" IS 'Foreign key to the source document. Source is specified by abbreviation (e.g., DB=court record).';
COMMENT ON COLUMN "public"."entries"."winner_id" IS 'Foreign key to the winning party of the legal case.';
COMMENT ON COLUMN "public"."entries"."legal_source_id" IS 'Foreign key to the legal source or precedent cited.';
COMMENT ON COLUMN "public"."entries"."land_rights_status" IS 'Indicates if the individual had land rights.';
COMMENT ON COLUMN "public"."entries"."judgement_id" IS 'Foreign key to the judgement or sanction given.';
COMMENT ON COLUMN "public"."entries"."placename_id" IS 'Foreign key to a standardized placename, from the Swedish National Survey (which enables GIS connection)';
COMMENT ON COLUMN "public"."entries"."lay_judge_involved" IS 'Flag (0/1) indicating if the district court''s board of lay judges (nämnd) played a role.';
COMMENT ON COLUMN "public"."entries"."season_id" IS 'Foreign key to the season when the event occurred.';
COMMENT ON COLUMN "public"."entries"."land_use_id" IS 'Foreign key to the resource or land use type involved in the event.';
COMMENT ON COLUMN "public"."entries"."entry_id" IS 'Primary key for the entries table.';
COMMENT ON COLUMN "public"."sources"."source_id" IS 'Primary key for the sources table.';
COMMENT ON COLUMN "public"."sources"."source_name" IS 'The full name of the historical source document.';
COMMENT ON COLUMN "public"."sources"."source_abbreviation" IS 'The abbreviation for the source, used for quick reference.';
COMMENT ON COLUMN "public"."land_use"."land_use_id" IS 'Primary key for the land use types table.';
COMMENT ON COLUMN "public"."land_use"."type" IS 'The type of land use or resource being discussed (e.g., ''Fishing rights'').';
COMMENT ON COLUMN "public"."persons"."person_id" IS 'Primary key for the persons table.';
-- COMMENT ON COLUMN "public"."persons"."individual_id" IS 'A unique identifier for the individual, possibly from an external genealogical system.';
-- COMMENT ON COLUMN "public"."persons"."father_id" IS 'Identifier for this person''s father, likely linking to another individual_id.';
-- COMMENT ON COLUMN "public"."persons"."mother_id" IS 'Identifier for this person''s mother, likely linking to another individual_id.';
COMMENT ON COLUMN "public"."persons"."given_name" IS 'The person''s given name(s) (first name).';
COMMENT ON COLUMN "public"."persons"."patronymic" IS 'The person''s patronymic name (e.g., ''Andersson'').';
-- COMMENT ON COLUMN "public"."persons"."birth_date" IS 'The specific date of birth, if known.';
COMMENT ON COLUMN "public"."persons"."birth_year" IS 'The year of birth.';
-- COMMENT ON COLUMN "public"."persons"."birth_place" IS 'The location of birth.';
-- COMMENT ON COLUMN "public"."persons"."residence_date" IS 'A specific year or date associated with the person''s residence.';
-- COMMENT ON COLUMN "public"."persons"."death_date" IS 'The specific date of death, if known.';
COMMENT ON COLUMN "public"."persons"."death_year" IS 'The year of death.';
-- COMMENT ON COLUMN "public"."persons"."death_place" IS 'The location of death.';
-- COMMENT ON COLUMN "public"."persons"."event_date" IS 'Date associated with a specific life event for this person.';
-- COMMENT ON COLUMN "public"."persons"."event_id" IS 'Identifier for a specific life event (e.g., marriage).';
COMMENT ON COLUMN "public"."persons"."surname" IS 'The person''s surname, byname, or family name.';
COMMENT ON COLUMN "public"."persons"."community_name" IS 'The name of the village where the person primarily resided.';
COMMENT ON COLUMN "public"."persons"."full_name" IS 'The person''s full name, likely a computed or concatenated field.';
COMMENT ON COLUMN "public"."legal_sources"."legal_source_id" IS 'Primary key for the legal sources table.';
COMMENT ON COLUMN "public"."legal_sources"."legal_source_name" IS 'The name of the legal source or legal precedent cited.';
COMMENT ON COLUMN "public"."parishes"."parish" IS 'Heading comes from the National Survey database of place names and means "parish or town", but only parishes are relevant here';
COMMENT ON COLUMN "public"."parishes"."parish_id" IS 'Primary key for the parishes table.';
COMMENT ON COLUMN "public"."winners"."winner_id" IS 'Primary key for the winners table.';
COMMENT ON COLUMN "public"."winners"."winner_description" IS 'Describes the winning party in a legal case (e.g., ''settler'' or ''reindeer herder'')';
